#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jaxrs-api
Version  : 2.1.5
Release  : 1
URL      : https://github.com/eclipse-ee4j/jaxrs-api/archive/2.1.5.tar.gz
Source0  : https://github.com/eclipse-ee4j/jaxrs-api/archive/2.1.5.tar.gz
Source1  : https://repo1.maven.org/maven2/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5/jakarta.ws.rs-api-2.1.5.jar
Source2  : https://repo1.maven.org/maven2/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5/jakarta.ws.rs-api-2.1.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: mvn-jaxrs-api-data = %{version}-%{release}
Requires: mvn-jaxrs-api-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
[//]: # "  "
[//]: # " This program and the accompanying materials are made available under the "
[//]: # " terms of the Eclipse Public License v. 2.0, which is available at "
[//]: # " http://www.eclipse.org/legal/epl-2.0. "
[//]: # "  "
[//]: # " This Source Code may also be made available under the following Secondary "
[//]: # " Licenses when the conditions for such availability set forth in the "
[//]: # " Eclipse Public License v. 2.0 are satisfied: GNU General Public License, "
[//]: # " version 2 with the GNU Classpath Exception, which is available at "
[//]: # " https://www.gnu.org/software/classpath/license.html. "
[//]: # "  "
[//]: # " SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 "

%package data
Summary: data components for the mvn-jaxrs-api package.
Group: Data

%description data
data components for the mvn-jaxrs-api package.


%package license
Summary: license components for the mvn-jaxrs-api package.
Group: Default

%description license
license components for the mvn-jaxrs-api package.


%prep
%setup -q -n jaxrs-api-2.1.5

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jaxrs-api
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-jaxrs-api/LICENSE.md
cp examples/LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-jaxrs-api/examples_LICENSE.md
mkdir -p %{buildroot}/usr/share/java/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5/jakarta.ws.rs-api-2.1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5/jakarta.ws.rs-api-2.1.5.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5/jakarta.ws.rs-api-2.1.5.jar
/usr/share/java/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5/jakarta.ws.rs-api-2.1.5.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jaxrs-api/LICENSE.md
/usr/share/package-licenses/mvn-jaxrs-api/examples_LICENSE.md
